FROM registry.fedoraproject.org/fedora:rawhide
RUN dnf -y install make tar python3-dnf-plugins-core go-rpm-macros git rpm-build dnf5-plugins
COPY weldr-client-*.tar.gz .
RUN mkdir /source && tar --strip=1 -C /source -xvf weldr-client-*.tar.gz
RUN cd /source && git config --global user.email "testing" && \
    git init && git add . && git commit -m "Build Test"
RUN cd /source && make builddep && make scratch-rpm
